### ISSUE TITLE
[Bug] RuntimeError: Expected object of type Variable... when trying to predict on datasets trained on more than 32767 datapoints

### ISSUE THREAD

**Issue by jgibson2** [cornellius-gp/gpytorch#951] opened 2019-11-17 08:22 UTC
# 🐛 Bug

When training on 1D Tensors of size > 32767 (larger than the signed integer maximum), a RuntimeError is thrown about expecting a Variable instead of a FloatTensor. Wrapping tensors in torch.autograd.Variable does not solve the issue. 

## To reproduce

** Code snippet to reproduce **
```python
"""
Type error thrown

Ref: https://github.com/cornellius-gp/gpytorch/blob/master/examples/04_Scalable_GP_Regression_1D/KISSGP_Regression_1D.ipynb
"""
import math
import torch
import gpytorch


class GPRegressionModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(GPRegressionModel, self).__init__(train_x, train_y, likelihood)

        # SKI requires a grid size hyperparameter.
        # This util can help with that. Here we are using a grid that
        # has the same number of points as the training data (a ratio of 1.0).
        # Performance can be sensitive to this parameter,
        # so you may want to adjust it for your own problem on a validation set.
        grid_size = gpytorch.utils.grid.choose_grid_size(train_x, 1.0)

        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.GridInterpolationKernel(
            gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel()),
            grid_size=grid_size, num_dims=1,
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

if __name__ == '__main__':

    training_iterations = 5

    # one greater than signed integer limit...
    train_x = torch.linspace(0, 100, 32768)
    train_y = train_x * (4 * math.pi) + torch.randn(train_x.size()) * 0.2

    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = GPRegressionModel(train_x, train_y, likelihood)

    # Find optimal model hyperparameters
    model.train()
    likelihood.train()

    # Use the adam optimizer
    optimizer = torch.optim.Adam([
        {'params': model.parameters()},  # Includes GaussianLikelihood parameters
    ], lr=0.5)

    # "Loss" for GPs - the marginal log likelihood
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    for i in range(training_iterations):
        optimizer.zero_grad()
        output = model(train_x)
        loss = -mll(output, train_y)
        loss.backward()
        print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
        optimizer.step()


    # Switch to evaluation mode
    model.eval()
    likelihood.eval()

    # The gpytorch.settings.fast_pred_var flag activates LOVE (for fast variances)
    # See https://arxiv.org/abs/1803.06058
    with torch.no_grad(), gpytorch.settings.fast_pred_var(), gpytorch.settings.max_root_decomposition_size(10):
        test_x = torch.round(torch.linspace(min(train_x), max(train_x), 1000))
        prediction = likelihood(model(test_x))
        mean = prediction.mean

        # Get lower and upper predictive bounds
        lower, upper = prediction.confidence_region()

    print(mean)
```

** Stack trace/error message **
```
Iter 1/5 - Loss: 681.360
Iter 2/5 - Loss: 347.955
Iter 3/5 - Loss: 202.934
Iter 4/5 - Loss: 132.062
Iter 5/5 - Loss: 94.708
Traceback (most recent call last):
  File "/home/john/workspace/bcaller/training_failure_example.py", line 74, in <module>
    prediction = likelihood(model(test_x))
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/models/exact_gp.py", line 291, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 494, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 499, in exact_predictive_mean
    precomputed_cache = self.mean_cache
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/models/exact_prediction_strategies.py", line 405, in mean_cache
    train_train_covar_inv_labels = train_train_covar_with_noise.inv_matmul(mean_diff)
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/lazy/lazy_tensor.py", line 928, in inv_matmul
    *self.representation(),
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/functions/_inv_matmul.py", line 46, in forward
    solves = _solve(lazy_tsr, right_tensor)
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/functions/_inv_matmul.py", line 14, in _solve
    return lazy_tsr._solve(rhs, preconditioner)
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/lazy/lazy_tensor.py", line 641, in _solve
    preconditioner=preconditioner,
  File "/home/john/workspace/bcaller/venv/lib/python3.6/site-packages/gpytorch/utils/linear_cg.py", line 208, in linear_cg
    torch.sum(mul_storage, -2, keepdim=True, out=alpha)
RuntimeError: Expected object of type Variable but found type torch.FloatTensor for argument #0 'self'
```

## Expected Behavior
Training and prediction to work without error.

## System information

**Please complete the following information:**
- GPyTorch version: 0.3.6
- Torch version: 1.3.1
- Ubuntu 14.04 LTS 64-bit

## Additional context

No documentation about large datasets mentioned this error.

**Comment by gpleiss** [comment] 2019-11-17 15:11
When I rerun your code I am not able to reproduce that error. Can you try running your code on the `master` branch of gpytorch? (E.g. pip install git+https://github.com/cornellius-gp/gpytorch.git)

In general, GPs are a lot more stable when you normalize your inputs/targets to have values roughly between -1 and 1. Right now your range is between 0-100 for x and similar for y.

**Comment by jgibson2** [comment] 2019-11-17 20:10
I tried changing the linspace to `torch.linspace(0, 1, 32768)` and ran on the master branch, but got the same error.

**Comment by Balandat** [comment] 2019-11-19 03:25
Hmm this is weird - on the python end there is no notion of a `Variable` in torch anymore. Changes to the C++ api that got rid of that just landed recently on pytorch master. Is this maybe a nightly version of pytorch that could be buggy in that respect?

**Comment by jgibson2** [comment] 2019-11-19 20:16
@Balandat this was the standard version of `torch` I got by running `pip3 install torch` on Python 3.6.8.

**Comment by gpleiss** [comment] 2019-11-20 00:37
@jgibson2 - what about running `conda install pytorch -c pytorch` instead?

**Comment by jgibson2** [comment] 2019-11-22 00:11
When I have a second I'll install `conda` and try this out.

**Closed** 2021-09-24 18:37 UTC
Labels: bug
