### ISSUE TITLE
Gaussian likelihood log noise

### ISSUE THREAD

**Issue by sumitsk** [cornellius-gp/gpytorch#176] opened 2018-07-15 01:48 UTC
I am considering the case when the log noise of Gaussian likelihood depends on the input but is known, so, the log noise is not a parameter but a known vector of measurement noise of all the training points. I have been able to implement and train a GP model where all the likelihood noise values are same. However, when noise values are different, I get a runtime error due to the following line
https://github.com/cornellius-gp/gpytorch/blob/c16ec465ee6e2d9d1a6aa60e303a1292439ea275/gpytorch/lazy/added_diag_lazy_variable.py#L41

Is it possible to have different known likelihood noise for different training points?

**Comment by jacobrgardner** [comment] 2018-07-15 02:54
It is possible! We implement input dependent noise as a kernel. Check out `gpytorch.kernels.WhiteNoiseKernel` and its associated unit tests https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_white_noise_regression.py and https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_kissgp_white_noise_regression.py

**Comment by jacobrgardner** [comment] 2018-07-16 18:20
Going to close this since the above should work out for you -- feel free to reopen if you have other issues with it!

**Closed by jacobrgardner** 2018-07-16 18:20 UTC
