### ISSUE TITLE
[Question] How/Where is the Gram Matrix stored and used during evaluation time?

### ISSUE THREAD

**Issue by xiaoyuxin1002** [cornellius-gp/gpytorch#1414] opened 2021-01-03 22:57 UTC
I am relatively new to GPyTorch and I am having a few doubts about the implementation:

Let's say I have a large training set X which is split equally into 2 halves X1 and X2.
1. In order to get the posterior f | X, can I fit the GPyTorch model on X1 first and then X2? Theoretically, I will get f | X1 after fitting the model on X1 and then get f | X1, X2 which is equivalent to f | X in the end, right?
2. After fitting the GPyTorch model on X1 and get the posterior f | X1, I want to make predictions on X2 with the posterior, how is the Gram Matrix of X1 learned and stored during training and used during predictions? Is there a way to fetch it? In this case, the output from the model forward() function is indeed the posterior multivariate normal distribution f(X2) | X1, right?
3. Do we have to switch the model into eval() mode during predictions? What exactly does eval() do in GPyTorch?

Thanks in advance!

**Comment by gpleiss** [comment] 2021-01-04 14:37
> Let's say I have a large training set X which is split equally into 2 halves X1 and X2.

Define "large." Too large to fit into memory all at once? If you can fit it all into memory at once, GPyTorch does a lot of optimizations under-the-hood - so you may not need to split it in half.

> What exactly does eval() do in GPyTorch?

After calling `model.train()`, the model outputs the prior distribution. After calling `model.eval()`, the model outputs the posterior distribution. So yes, it needs to be in `eval` mode to make predictions.

> In order to get the posterior f | X, can I fit the GPyTorch model on X1 first and then X2?

This is possible, though in GPyTorch you'd have to construct nested GP models. This would be rather complicated to implement in code.

> how is the Gram Matrix of X1 learned and stored during training and used during predictions? Is there a way to fetch it?

It is lazily evaluated. Why do you want to fetch it?

**Comment by xiaoyuxin1002** [comment] 2021-01-04 19:51
1. For example, in the following code snippet, I want to fit the model on X1 first and then on X2. Am I correct about the usage of `set_train_data()`?
```
model = GP(train_x1, train_y1, likelihood)

model.train()
likelihood.train()

# fitting on X1
output = model(train_x1)
loss = -mll(output, train_y1)
loss.backward()    
optimizer.step()
optimizer.zero_grad()

# fitting on X2
model.set_train_data(train_x2, train_y2)
output = model(train_x2)
loss = -mll(output, train_y2)
loss.backward()    
optimizer.step()
optimizer.zero_grad()
```
The training set is just too large to fit into the memory at once, so are there any good methods for scaling up the GP?

2. After fitting the model on X1, I would like to output f(X2) | X1. However, I found some confusing comments about how the predictions are computed in #1200 

> the first time you call forward after model.eval() will always be on the training data since it needs to compute the prediction caches

So am I correct about outputting f(X2) | X1 using the following code snippet?

```
model = GP(train_x1, train_y1, likelihood)

model.train()
likelihood.train()

# fitting on X1
output = model(train_x1)
loss = -mll(output, train_y1)
loss.backward()    
optimizer.step()
optimizer.zero_grad()

model.eval()
likelihood.eval()

# is output f(X2) | X1?
with torch.no_grad(), gpytorch.settings.fast_pred_var():
        output = model(train_x2)
```
If I am also going to fit the model on X2 afterward, can I use `get_fantasy_model()` in the following way?
```
model = model.get_fantasy_model(train_x2, train_y2)
output = model(train_x2)
loss = -mll(output, train_y2)
loss.backward()    
optimizer.step()
optimizer.zero_grad()
```

3. My forward function has some customized inputs in addition to train_X. However, I encountered some errors when using the following code snippet. So what is the difference between calling `output = model(train_x, a, b)` and `output = model.forward(train_x, a, b)`?

```
class MyGP(gpytorch.models.ExactGP):
    def __init__(self, train_X, train_Y, likelihood):        
        super(MyGP, self).__init__(train_X, train_Y, likelihood)
    def forward(self, train_X, a, b):
        # some computations here
        return gpytorch.distributions.MultivariateNormal(mean_X, covar_X)

output = model(train_x, a, b) # Some errors occurred by doing so
output = model.forward(train_x, a, b) # This worked fine
```

4. I also wish to define my own Kernel class, do I only need to extend the Kernel base class by implementing the __init__() and forward() in the following way, then GPyTorch will handle everything else (such as the computation of the posterior) for me?
```
class MyKernel(gpytorch.kernel.Kernel):
    def __init__(self):        
        super(MyKernel, self).__init__()
    def forward(self, train_X):
        # some computations here
        return covar_matrix

class MyGP(gpytorch.models.ExactGP):
    def __init__(self, train_X, train_Y, likelihood):        
        super(MyGP, self).__init__(train_X, train_Y, likelihood)
        self.covar_module = MyKernel()
    def forward(self, train_X, a, b):
        # some computations here
        covar_X = self.covar_module(train_X)
        return gpytorch.distributions.MultivariateNormal(mean_X, covar_X)
```

Sorry about the overwhelming amount of questions. Really need some help here.  Much appreciated.

**Comment by gpleiss** [comment] 2021-02-18 14:28
> The training set is just too large to fit into the memory at once, so are there any good methods for scaling up the GP?

If the training data is too large to fit into memory, you'll need a method that supports minibatching. I would try [SVGP regression](https://docs.gpytorch.ai/en/latest/examples/04_Variational_and_Approximate_GPs/SVGP_Regression_CUDA.html).

> So am I correct about outputting f(X2) | X1 using the following code snippet?

This code snippet is correct

> If I am also going to fit the model on X2 afterward, can I use get_fantasy_model() in the following way?

That seems to be correct

> My forward function has some customized inputs in addition to train_X. However, I encountered some errors when using the following code snippet. So what is the difference between calling output = model(train_x, a, b) and output = model.forward(train_x, a, b)?

Could you open up a separate issue for this point?

> I also wish to define my own Kernel class, do I only need to extend the Kernel base class by implementing the init() and forward() in the following way, then GPyTorch will handle everything else (such as the computation of the posterior) for me?

See the [implementing a custom kernel tutorial](https://docs.gpytorch.ai/en/latest/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html)


I'm going to close this issue for now. Could you:
- Open up a separate issue for the `model.forward(train_x, a, b)` errors?
- Start a [Discussion topic](https://github.com/cornellius-gp/gpytorch/discussions) if you want any follow-up to your other questions?

Thanks!

**Closed by gpleiss** 2021-02-18 14:28 UTC
