### ISSUE TITLE
[Docs] Pointer to get started with (bayesian) GPLVM

### ISSUE THREAD

**Issue by holmrenser** [cornellius-gp/gpytorch#1041] opened 2020-02-06 09:33 UTC
I am in the process of exploring gpytorch from some of my GP applications. Currently I use pyro for GPLVM tasks (i.e. https://pyro.ai/examples/gplvm.html). I am always interested in trying out various approaches, so I would like to see how I can do similar things in gpytorch.

Specifically, I am interested in the bayesian GPLVM as described in [Titsias et al 2010].

I have found some documentation on handling uncertain inputs, so I am guessing that would be a good place to start, but I would love to hear some thoughts from any of the gpytorch developers.

[Titsias et al 2010]: http://proceedings.mlr.press/v9/titsias10a/titsias10a.pdf

**Comment by holmrenser** [comment] 2020-02-06 16:49
For what it's worth: this is what I have come up with so for, but it doesn't quite work yet.
(I combined some ideas from the multitask learning and uncertain inputs examples)

```
from matplotlib import pyplot as plt
import torch

from gpytorch.models import ApproximateGP
from gpytorch.variational import CholeskyVariationalDistribution, VariationalStrategy
from gpytorch.means import ConstantMean
from gpytorch.kernels import ScaleKernel, RBFKernel
from gpytorch.distributions import MultitaskMultivariateNormal, MultivariateNormal
from gpytorch.likelihoods import MultitaskGaussianLikelihood, GaussianLikelihood
from gpytorch.priors import NormalPrior

from gpytorch.mlls import VariationalELBO
from tqdm.notebook import tqdm

import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

n_latent_dims = 2
n_data_dims = 3

# training data is two gaussian blobs at [10, 10, 10] and [1, 1, 1].
y1 = torch.distributions.Normal(
    torch.tensor([10.] * n_data_dims),
    torch.tensor([1.] * n_data_dims)
).sample([10])

y2 = torch.distributions.Normal(
    torch.tensor([1.] * n_data_dims),
    torch.tensor([1.] * n_data_dims)
).sample([10])

train_y = torch.cat([y1, y2])


class bGPLVM(ApproximateGP):
    def __init__(self, n_inducing_points, n_latent_dims, n_data_points):
        inducing_points = torch.randn(n_inducing_points, n_latent_dims)
        variational_distribution = CholeskyVariationalDistribution(
            inducing_points.size(0)
        )
        variational_strategy = VariationalStrategy(
            self, inducing_points, variational_distribution, 
            learn_inducing_locations=True
        )
        super(bGPLVM, self).__init__(variational_strategy)
        batch_shape = torch.Size([n_data_dims])
        self.mean_module = ConstantMean(batch_shape=batch_shape)
        self.covar_module = ScaleKernel(
            RBFKernel(batch_shape=batch_shape),
            batch_shape=batch_shape
        )
        self.X = torch.nn.Parameter(
                torch.randn(n_data_points, n_latent_dims)
            )
        self.register_parameter(
            name="X", 
            parameter=self.X
        )
       self.register_prior('prior_X', NormalPrior(0, 1), 'X')
        
    def forward(self):
        mean_x = self.mean_module(self.X)
        covar_x = self.covar_module(self.X)
        dist = MultitaskMultivariateNormal.from_batch_mvn(
            MultivariateNormal(mean_x, covar_x)
        )
        return dist

model = bGPLVM(n_inducing_points=10, n_latent_dims=n_latent_dims, n_data_points = 20)
likelihood = MultitaskGaussianLikelihood(num_tasks=n_data_dims)

model.train()
likelihood.train()

optimizer = torch.optim.SGD([
    {'params': model.parameters()},
    {'params': likelihood.parameters()},
], lr=0.01)

mll = VariationalELBO(likelihood, model, num_data=train_y.size(0))

iterator = tqdm(range(2000))
for i in iterator:
    optimizer.zero_grad()
    output = model.forward()
    loss = -mll(output, train_y)
    iterator.set_postfix(loss=loss.item())
    loss.backward(retain_graph=True)
    optimizer.step()

plt.scatter(
    *model.X.detach().numpy().T,
    c=[*['red'] * 10, *['blue']*10],
    alpha=.5
)
```

With this setup it seems like the latent variables are changing during training, but I am having a hard time figuring out whether it makes sense what I am doing.

Any comments are welcome!

**Comment by jacobrgardner** [comment] 2020-02-08 02:02
Hi @holmrenser,

The approach you set up seems generally reasonable to me --are there specific things that are not working?

If you are already using pyro, one option would be to use the pyro + gpytorch interface, with pyro doing inference over the latent variables and gpytorch giving you some more flexibility when defining GP models.

**Comment by holmrenser** [comment] 2020-02-10 13:27
It's nice to hear my approach seems to make sense! Unfortunately the location of the latent points does not seem to make any sense so far... In the gaussian blobs example I included, there should be two clearly separated groups of points. However after training, everything is mixed.

I have set up a google colab notebook with a reproduction: https://colab.research.google.com/drive/1J1RmU0C-qw8JpgVBYUJ39SQ4qsl4tnBP

It feels like I'm missing something...

**Comment by holmrenser** [comment] 2020-02-10 15:09
One (perhaps critical) difference I have just noticed is that during training, I am calling `model.forward()` instead of `model()`. I figured that since the model's `X` is a latent variable, it would make no sense to specify it in the model call. I assumed `__call__()` would just be the same as calling `forward()`. However, I just learned that under the hood `ApproximateGP`  calls `self.variational_strategy`, and not `self.forward`.

I then tried the following:

```
class bGPLVM(ApproximateGP):
    # Same __init__ as above
        
    def forward(self, X):
        mean_x = self.mean_module(X)
        covar_x = self.covar_module(X)
        dist = MultitaskMultivariateNormal.from_batch_mvn(
            MultivariateNormal(mean_x, covar_x)
        )
        return dist

for i in iterator:
    optimizer.zero_grad()
    output = model(model.X)          <-------- THIS IS DIFFERENT
    loss = -mll(output, train_y)
    iterator.set_postfix(loss=loss.item())
    loss.backward(retain_graph=True)
    optimizer.step()
```

This makes that `self.model.forward` is called in the `variationalstrategy.forward` call, but this is failing when trying to calculate `test_mean` in `VariationalStrategy.forward`.

For some reason the shape of my inducing points seems off, because I end up with a `test_mean` that is empty. I think the slice happening [here](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/variational/variational_strategy.py#L91) is supposed to leave the original data, but in my case it removes everything.

**Comment by jacobrgardner** [comment] 2020-02-11 18:36
@holmrenser Got a chance to look more carefully at your code. Sorry it took a bit of time to get around to! 

It looks like your problems can be solved by using the standard batch GP interface rather than the independent multitask one (see [here](https://github.com/cornellius-gp/gpytorch/blob/master/examples/08_Advanced_Usage/Simple_Batch_Mode_GP_Regression.ipynb) for the relevant tutorial notebook).

Here is a version of your code that I've patched up that seems to be working in the sense that the final plot is clearly two distinct Gaussians:
```python
from matplotlib import pyplot as plt
import torch

from gpytorch.models import ApproximateGP
from gpytorch.variational import CholeskyVariationalDistribution, VariationalStrategy
from gpytorch.means import ConstantMean
from gpytorch.kernels import ScaleKernel, RBFKernel
from gpytorch.distributions import MultitaskMultivariateNormal, MultivariateNormal
from gpytorch.likelihoods import MultitaskGaussianLikelihood, GaussianLikelihood
from gpytorch.priors import NormalPrior

from gpytorch.mlls import VariationalELBO
from tqdm.notebook import tqdm

import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

n_latent_dims = 2
n_data_dims = 3

# training data is two gaussian blobs at [10, 10, 10] and [1, 1, 1].
y1 = torch.distributions.Normal(
    torch.tensor([10.] * n_data_dims),
    torch.tensor([1.] * n_data_dims)
).sample([10])

y2 = torch.distributions.Normal(
    torch.tensor([1.] * n_data_dims),
    torch.tensor([1.] * n_data_dims)
).sample([10])

train_y = torch.cat([y1, y2]).transpose(-2, -1)


class bGPLVM(ApproximateGP):
    def __init__(self, n_inducing_points, n_latent_dims, n_data_points):
        batch_shape = torch.Size([n_data_dims])
        inducing_points = torch.randn(n_data_dims, n_inducing_points, n_latent_dims)
        variational_distribution = CholeskyVariationalDistribution(
            inducing_points.size(-2), batch_shape=batch_shape,
        )
        variational_strategy = VariationalStrategy(
            self, inducing_points, variational_distribution, 
            learn_inducing_locations=True
        )
        super(bGPLVM, self).__init__(variational_strategy)
        self.mean_module = ConstantMean(batch_shape=batch_shape)
        self.covar_module = ScaleKernel(
            RBFKernel(batch_shape=batch_shape),
            batch_shape=batch_shape
        )
        self.X = torch.nn.Parameter(
                torch.randn(n_data_points, n_latent_dims)
            )
        self.register_parameter(
            name="X", 
            parameter=self.X
        )
        self.register_prior('prior_X', NormalPrior(0, 1), 'X')
        
    def forward(self, X):
        mean_x = self.mean_module(X)
        covar_x = self.covar_module(X)
        dist = MultivariateNormal(mean_x, covar_x)
        return dist

model = bGPLVM(n_inducing_points=10, n_latent_dims=n_latent_dims, n_data_points = 20)
likelihood = GaussianLikelihood(num_tasks=n_data_dims, batch_shape=torch.Size([n_data_dims]))

model.train()
likelihood.train()

optimizer = torch.optim.SGD([
    {'params': model.parameters()},
    {'params': likelihood.parameters()},
], lr=0.01)

mll = VariationalELBO(likelihood, model, num_data=train_y.size(0))

iterator = tqdm(range(2000))
for i in iterator:
    optimizer.zero_grad()
    output = model(model.X)
    loss = -mll(output, train_y).mean()
    iterator.set_postfix(loss=loss.item())
    loss.backward(retain_graph=True)
    optimizer.step()

plt.scatter(
    *model.X.detach().numpy().T,
    c=[*['red'] * 10, *['blue']*10],
    alpha=.5
)
```

**Comment by jacobrgardner** [comment] 2020-02-11 18:40
@holmrenser By the way -- if the above ends up working as you'd expect, we'd definitely welcome a pull request for a GP-LVM tutorial. I don't think this is the first time we'd gotten that asked about.

Also: You may want to play around with making the inducing points equal to model.X -- is it standard to use inducing points as well as the latent variables for GP-LVMs? I'm not very familiar with recent literature on that stuff.

**Comment by holmrenser** [comment] 2020-02-11 18:53
Awesome! I'll experiment a little with your example and will report back. I am definitely thinking of contributing some docs if everything works out, so expect a PR shortly!

As for the inducing points: it is my understanding that the inducing points are part of the variational approximation to the full posterior and hence make the distinction between the bayesian GPLVM ([Titsias & Lawrence 2010](http://proceedings.mlr.press/v9/titsias10a/titsias10a.pdf)) and the original type II ML optimized GPLVM ([Lawrence 2004](https://papers.nips.cc/paper/2540-gaussian-process-latent-variable-models-for-visualisation-of-high-dimensional-data.pdf)).

**Comment by gpleiss** [comment] 2020-02-11 19:00
Hi @holmrenser - sorry for the slow reply - I'm bogged down with KDD right now.

In general, approximate GP models cannot have a `MultitaskMultivariateNormal` returned by the forward function (@jacobrgardner we should maybe add an error for this).

You can either use the batched-GP approach that @jacobrgardner recommends, or you can wrap the variational strategy with a `MultitaskVariationalStrategy`:

```python
        variational_strategy = gpytorch.variational.MultitaskVariationalStrategy(VariationalStrategy(
            self, inducing_points, variational_distribution, 
            learn_inducing_locations=True
        ), num_tasks=num_tasks)
```

When you call the `bGPLVM` model, the output will be a MultitaskMultivariateNormal.

**Comment by davindicode** [comment] 2020-06-02 19:24
Hey just a question, thanks for sharing the GPLVM code! How would you compute the uncertainty in the learned X however, as they do in Lawrence 2005? Do we have access to the distribution over X conditioned on the observed data?

**Comment by holmrenser** [comment] 2020-06-05 12:54
@davindicode I had to think on that for a while! If I am not mistaken, in Lawrence 2005 there is no distribution over X, and instead X is optimized (see fig.2 in the paper as well). What tripped me up is the visualization of uncertainty in the latent space (like in fig. 1b), but I think the key there is that the shading is based on the uncertainty in the _data space_, which is something you can easily get from the GP model by calling the `confidence_region` method. 

Correct me if I'm wrong though!

**Comment by jrojsel** [comment] 2020-06-09 15:39
Hi,

I tried this out by following @jacobrgardner's code above. I tried to reproduce the Pyro tutorial ([here](https://pyro.ai/examples/gplvm.html)), and it worked :) Note that the objective for optimization should (?) be the sum of the likelihood for the GP's, not the mean. Code:

```python
from matplotlib import pyplot as plt
import torch

from gpytorch.models import ApproximateGP
from gpytorch.variational import CholeskyVariationalDistribution, VariationalStrategy
from gpytorch.means import ConstantMean, LinearMean
from gpytorch.kernels import ScaleKernel, RBFKernel, MaternKernel
from gpytorch.distributions import MultitaskMultivariateNormal, MultivariateNormal
from gpytorch.likelihoods import MultitaskGaussianLikelihood, GaussianLikelihood
from gpytorch.priors import NormalPrior

from gpytorch.mlls import VariationalELBO, PredictiveLogLikelihood
from tqdm.notebook import tqdm

import pandas as pd
from torch.nn import Parameter

import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

URL = "https://raw.githubusercontent.com/sods/ods/master/datasets/guo_qpcr.csv"

df = pd.read_csv(URL, index_col=0)
print("Data shape: {}\n{}\n".format(df.shape, "-" * 21))
print("Data labels: {}\n{}\n".format(df.index.unique().tolist(), "-" * 86))
print("Show a small subset of the data:")
df.head()

data = torch.tensor(df.values, dtype=torch.get_default_dtype())
# we need to transpose data to correct its shape
train_y_pyro = data.t()

capture_time = train_y_pyro.new_tensor([int(cell_name.split(" ")[0]) for cell_name in df.index.values])
# we scale the time into the interval [0, 1]
time = capture_time.log2() / 6

X_prior_mean = torch.zeros(train_y_pyro.size(1), 2)  # shape: 437 x 2
X_prior_mean[:, 0] = time

train_y = train_y_pyro
n_data_dims = train_y.shape[0]
n_latent_dims = 2


class bGPLVM(ApproximateGP):
    def __init__(self, n_inducing_points, n_latent_dims, n_data_points):
        batch_shape = torch.Size([n_data_dims])
        inducing_points = torch.randn(n_data_dims, n_inducing_points, n_latent_dims)
        variational_distribution = CholeskyVariationalDistribution(
            inducing_points.size(-2), batch_shape=batch_shape,
        )
        variational_strategy = VariationalStrategy(
            self, inducing_points, variational_distribution, 
            learn_inducing_locations=True
        )
        super(bGPLVM, self).__init__(variational_strategy)
        self.mean_module = ConstantMean(batch_shape=batch_shape)
        self.covar_module = ScaleKernel(
            RBFKernel(nu=1.5,batch_shape=batch_shape, ard_num_dims=2),
            batch_shape=batch_shape
        )
        
        # using time as the prior mean in the x-direction as in he Pyro tutorial
        self.X = Parameter(X_prior_mean.clone())
        self.register_parameter(
            name="X", 
            parameter=self.X
            )
        self.register_prior('prior_X', NormalPrior(X_prior_mean,torch.ones_like(X_prior_mean)), 'X')
        
    def forward(self, X):
        mean_x = self.mean_module(X)
        covar_x = self.covar_module(X)
        dist = MultivariateNormal(mean_x, covar_x)
        return dist

model = bGPLVM(n_inducing_points=32, n_latent_dims=n_latent_dims, n_data_points = train_y.shape[1])
likelihood = GaussianLikelihood(num_tasks=n_data_dims, batch_shape=torch.Size([n_data_dims]))

model.train()
likelihood.train()

optimizer = torch.optim.Adam([
    {'params': model.parameters()},
    {'params': likelihood.parameters()},
], lr=0.01)

mll = PredictiveLogLikelihood(likelihood, model, num_data=train_y.size(0))

try:
    model.load_state_dict(torch.load("hypers.mod"))
    print("Hypers loaded")
except:
    loss_list = []
    iterator = tqdm(range(1000))
    for i in iterator:
        optimizer.zero_grad()
        output = model(model.X)
        loss = -mll(output, train_y).sum()
        loss_list.append(loss.item())
        print(str(loss.item()) + ", iter no: " + str(i))
        iterator.set_postfix(loss=loss.item())
        loss.backward(retain_graph=True)
        optimizer.step()
        
    torch.save(model.state_dict(),"hypers.mod")

plt.figure(figsize=(8, 6))
colors = plt.get_cmap("tab10").colors[::-1]
labels = df.index.unique()

X = model.X.detach().numpy()
for i, label in enumerate(labels):
    X_i = X[df.index == label]
    plt.scatter(0.5*X_i[:, 0], -X_i[:, 1], c=[colors[i]], label=label)

plt.legend()
plt.xlabel("pseudotime", fontsize=14)
plt.ylabel("branching", fontsize=14)
plt.title("GPLVM on Single-Cell qPCR data", fontsize=16)
plt.grid(True)
plt.show()
```

I'm currently experimenting with various kernels and priors.

One could also visualize the "magnification factor", i.e., the determinant of the metric tensor corresponding to the generative mapping from the latent space to the data space:

![Figure_1](https://user-images.githubusercontent.com/55212242/84167075-0d0c6380-aa76-11ea-94dd-c067e53aa939.png)

I'll have to check whether my code for doing that is appropriate though... Fetching n Jacobians from the model's computational graph, where n is the number of points to plot (here I think I used 30 x 30) is quite expensive.

@holmrenser Are you interested in implementing the [DP-GP-LVM](http://proceedings.mlr.press/v97/lawrence19a/lawrence19a.pdf) as well? 

It would be really interesting as it seems to be a very powerful framework for learning dependency structures. I am currently trying to figure out how to incorporate the Dirichlet process prior in the GP class. I think GPLVM's in general would really benefit from GPyTorch's fast computational backend as well as the KeOps integration (haven't tried this yet though).

**Comment by holmrenser** [comment] 2020-06-09 17:27
@jrojsel awesome, and great catch with the sum instead of mean as well!

As for the DP-GPLVM, I would totally be interested in spending some thought/time on that. The lawrence et al paper has been open in my browser tabs for ages, so this would be the perfect opportunity to get started.

How about I open a PR with regular and bayesian GPLVM tutorials somewhere this/next week, and then we can build from that?

**Comment by jrojsel** [comment] 2020-06-11 10:03
@holmrenser Sound good :) I'll have a look at the back constraints paper!

**Comment by vr308** [comment] 2020-12-30 03:20
Great effort! 

The implementation above definitely works but I am trying to wrap my head around two things:

 1) **_batch_shape_** (provided to GaussianLikelihood) -> I guess this comes from the fact that we are learning a batch of GPs (one per dimension). 

2) Why do we need **_num_tasks = n_data_dims_** (I just trained it with num_tasks = 2) and the result didn't change much.

**Comment by vr308** [comment] 2021-01-04 00:05
@holmrenser @jrojsel  it seems like the implementation above doesn't learn a distribution over X (there is a prior over X) but X is learnt as a model parameter (like the covariance hypers)-> this is different to the Bayesian GPLVM where you want to learn a location and diagonal covariance for each latent point in X.

```
for i in model.named_parameters():
    print(i[0])
```
```
X
variational_strategy.inducing_points
variational_strategy._variational_distribution.variational_mean # this is the m for q(u) ~ N(m,S)
variational_strategy._variational_distribution.chol_variational_covar # this is the L for q(u) ~ N(m,S) where S = LL^T
mean_module.constant
kernel.raw_outputscale
kernel.base_kernel.raw_lengthscale
likelihood.noise_covar.raw_noise
```
Any thoughts?

**Comment by holmrenser** [comment] 2021-05-19 09:13
@vr308 I'm finally getting back to this and just saw #1605, fantastic effort! Looking forward to the PR getting merged, in the meantime I'll try out your code on some of my datasets.

**Comment by gpleiss** [comment] 2021-06-10 00:33
I'm going to close this issue now that #1605 is merged in.

**Closed by gpleiss** 2021-06-10 00:33 UTC
Labels: documentation
