### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by neuronphysics** [cornellius-gp/gpytorch#2186] opened 2022-11-06 16:03 UTC
# 🐛 Bug

Hi,

I have been trying to build a model to learn the transition function for environment. I combined RNN with a multitask Gaussian process layer but unfortunately they won't work together. Here is my code: 
```
class MlpRnnEncoder(nn.Module):
    def __init__(self, seq_len, input_dim, encoder_hidden_size, rnn_hidden_size, num_layers, n_action=0, embed_dim=4, batch_size=200, dropout_rate=0.25, rnn_cell_type='GRU',  normalize=False):

        super(MlpRnnEncoder, self).__init__()
        self.normalize = normalize
        self.seq_len = seq_len
        self.input_dim = input_dim
        self.encoder_hidden_dim = encoder_hidden_size
        self.rnn_hidden_dim = rnn_hidden_size
        self.num_layers = num_layers
        self.rnn_cell_type = rnn_cell_type
        self.n_action = n_action
        if n_action != 0:
            self.act_embedding = nn.Embedding(n_action, embed_dim)
        self._batch_size = batch_size
        self.encoder = nn.Sequential()
        self.encoder.add_module('mlp_0', nn.Linear(input_dim, encoder_hidden_size))
        self.encoder.add_module('relu', nn.ReLU())
        self.encoder.add_module('dropout', nn.Dropout(dropout_rate))
        self.encoder.add_module('mlp_1', nn.Linear( encoder_hidden_size, rnn_hidden_size))
        self.encoder.add_module('relu', nn.ReLU())
        self.encoder.add_module('dropout', nn.Dropout(dropout_rate))
        #weight initialize
        weights_init(self.encoder, type='xavier')

        if self.rnn_cell_type == 'GRU':
            print('Using GRU as the recurrent layer.')
            self.rnn = nn.GRU(input_size=rnn_hidden_size, hidden_size=rnn_hidden_size, num_layers =num_layers, batch_first=True)
        elif self.rnn_cell_type == 'LSTM':
            print('Using LSTM as the recurrent layer.')
            self.c0 = torch.zeros(self.num_layers, batch_size , self.rnn_hidden_dim, device=device, requires_grad=False )
            self.rnn = nn.LSTM(input_size=rnn_hidden_size, hidden_size=rnn_hidden_size, num_layers =num_layers, batch_first=True)
        else:
            print('Using the default recurrent layer: RNN.')
            self.rnn = nn.RNN(input_size=rnn_hidden_size, hidden_size=rnn_hidden_size, num_layers =num_layers, batch_first=True)
            self.rnn_cell_type = 'RNN'
        self.init_params() #initialize RNN layer 
        #using information from all hidden states 
        self.h0 = torch.zeros(self.num_layers, batch_size, self.rnn_hidden_dim, device=device, requires_grad=False )

        self.traj_embed_layer = nn.Linear(2*rnn_hidden_size, rnn_hidden_size)
        self.traj_embed_layer.weight = torch.nn.init.xavier_normal_(self.traj_embed_layer.weight, gain=1)

        self.to(device)

    def init_params(self):
        for i in range(self.rnn.num_layers):
            nn.init.orthogonal_(getattr(self.rnn, f'weight_hh_l{i}'))
            nn.init.kaiming_normal_(getattr(self.rnn, f'weight_ih_l{i}'))
            nn.init.constant_(getattr(self.rnn, f'bias_hh_l{i}'), val=0)
            nn.init.constant_(getattr(self.rnn, f'bias_ih_l{i}'), val=0)
            

    def forward(self, x, y):


        if self.n_action != 0:
            y = self.act_embedding(y)
        if len(x.shape) != len(y.shape):
            y = torch.unsqueeze(y,-1)
        
        max_seq_lengths=x.shape[1]
        input = torch.cat((x, y), -1).float()
        
        state_size =input.shape[-1]
        mlp_encoded = self.encoder(input) # (N, T, Hiddens[-2]) get the hidden representation of every time step.
        
        sequence_length=[estimate_sequence_length(x[i,:,:]).item() if estimate_sequence_length(x[i,:,:]).numel()!=0 else max_seq_lengths for i in range(x.shape[0]) ]
        #print(f" Seq. Length:{sequence_length}")

        pad_embed_packoutput = torch.nn.utils.rnn.pack_padded_sequence(mlp_encoded, lengths=sequence_length, enforce_sorted=False,batch_first=True)
        
        #print(f"pad input rnn {pad_embed_packoutput[0].shape}")
        #forward prop
        if self.rnn_cell_type in ['GRU', 'RNN']:
           
            step_embed, traj_embed = self.rnn(pad_embed_packoutput, self.h0) #the first one is important and secound one is the hidden state
        else:
            
            step_embed, (traj_embed, _) = self.rnn(pad_embed_packoutput, (self.h0, self.c0))
        

        
        unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(step_embed, batch_first=True, total_length=max_seq_lengths)

        last_hidden_layer=traj_embed[-1,:,:]
        last_hidden_layer = last_hidden_layer[:, None, :].repeat(1, max_seq_lengths, 1) # (N, D) -> (N, T, D)

        features = torch.cat([unpacked, last_hidden_layer], dim=-1) # (N, T, 2D)
        
        features_reshaped = features.view(x.size(0)*x.size(1), features.size(-1))
        
                
        traj_embed = self.traj_embed_layer(features_reshaped) # (batch_size, hidden_dim)

        return  traj_embed

class DGPHiddenLayer(DeepGPLayer):
    def __init__(self, input_dims, output_dims, num_tasks, num_inducing=128, Matern_kernel_nu=2.5, mean_type = None):
        inducing_points = torch.randn(output_dims, num_inducing, input_dims)
        batch_shape = torch.Size([output_dims])

        variational_distribution = TrilNaturalVariationalDistribution(
            num_inducing_points=num_inducing,
            batch_shape=batch_shape,
            mean_init_std=0.
        )
        
        
        variational_strategy = gpytorch.variational.MultitaskVariationalStrategy(
            gpytorch.variational.VariationalStrategy(
              self, 
              inducing_points,
              variational_distribution,
              learn_inducing_locations=True), num_tasks=num_tasks, task_dim=-1)

        super().__init__(variational_strategy, input_dims, output_dims)
        if mean_type is None or mean_type=='constant':
          self.base_mean_module = ConstantMean(batch_shape=batch_shape) 
        elif mean_type=='linear':
           self.base_mean_module = gpytorch.means.LinearMean(input_dims, batch_shape=batch_shape)
        elif mean_type=='zero':
          self.base_mean_module = gpytorch.means.ZeroMean(batch_shape=batch_shape)

        self.mean_module = gpytorch.means.MultitaskMean(self.base_mean_module, num_tasks=num_tasks)
        lengthscale_prior = gpytorch.priors.NormalPrior(0.0, 1.0)
        lengthscale_constraint = None

        self.covar_module = gpytorch.kernels.MultitaskKernel(
            RBFKernel(batch_shape=batch_shape, # to set separate lengthscale for each eventuall batch
                      ard_num_dims=input_dims,
                      #active_dims=(0), # set input dims to compute covariance for, tuple of ints corresponding to indices of dimensions
                      lengthscale_constraint=lengthscale_constraint,
                      lengthscale_prior=lengthscale_prior), num_tasks=num_tasks, rank=1
        )
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)
    def __call__(self, inputs, are_samples=False, **kwargs):
        """
        Slightly adapted from original GPyTorch code to allow LMC in deep layer
        """
        deterministic_inputs = not are_samples
        if isinstance(inputs, MultitaskMultivariateNormal):
            inputs = torch.distributions.Normal(loc=inputs.mean, scale=inputs.variance.sqrt()).rsample()
            deterministic_inputs = False

        if gpytorch.settings.debug.on():
            if not torch.is_tensor(inputs):
                raise ValueError(
                    "`inputs` should either be a MultitaskMultivariateNormal or a Tensor, got "
                    f"{inputs.__class__.__Name__}"
                )

            if inputs.size(-1) != self.input_dims:
                raise RuntimeError(
                    f"Input shape did not match self.input_dims. Got total feature dims [{inputs.size(-1)}],"
                    f" expected [{self.input_dims}]"
                )

        # Repeat the input for all possible outputs
        if self.output_dims is not None:
            inputs = inputs.unsqueeze(-3)
            inputs = inputs.expand(*inputs.shape[:-3], self.output_dims, *inputs.shape[-2:])


        # Now run samples through the GP
        output = ApproximateGP.__call__(self, inputs)

        ###############################################
        # Removed block diagonalization of batched GPs
        ###############################################
        return output
class DeepLMC(DeepGP):
    def __init__(self, 
                 train_input_dim, 
                 seq_len, 
                 embed_dim, 
                 encoder_hidden_size, 
                 rnn_hidden_size,
                 num_layers,
                 state_dims,
                 action_dims,
                 batch_size,
                 normalize=False,
                 n_action=0, 
                 num_tasks=129, 
                 num_hidden_dgp_dims=5, 
                 num_inducing1=128, 
                 Matern_kernel_nu=1.5, 
                 mean_type=None,
                 rnn_cell_type='GRU',
                 dropout_rate=0.25,
                 clip_gradient_norm=2.0,              
                 ):

        super(DeepLMC,self).__init__()
        self.seq_len = seq_len
        self._clip_gradient_norm =clip_gradient_norm
        self.encoderRNN = MlpRnnEncoder(seq_len, train_input_dim, encoder_hidden_size, rnn_hidden_size, num_layers, n_action, embed_dim, batch_size, dropout_rate, rnn_cell_type, normalize)
        print(f"size of input:{self.encoderRNN.traj_embed_layer.out_features}")
        hidden_layer1 = DGPHiddenLayer(
            input_dims= self.encoderRNN.traj_embed_layer.out_features,
            output_dims=num_hidden_dgp_dims,
            num_tasks=num_tasks,
            num_inducing=num_inducing1,
            Matern_kernel_nu=Matern_kernel_nu,
            mean_type=mean_type
        )

        self.state_dims= state_dims
        self.action_dims= action_dims
        self.hidden_layer1 = hidden_layer1
        self.last_layer = last_layer

        self.likelihood = MultitaskGaussianLikelihood(num_tasks=num_tasks, rank=0)

    def forward(self, input):

        x = input[:,:,:self.state_dims]
        y = input[:,:, self.state_dims:]
        #print(f"shape of state {x.shape} and action {y.shape}")
        assert (y.shape[-1]==self.action_dims, f"number of dimension y {y.shape[-1]} expected to be equal with: {self.action_dims}")
        traj_embedding = self.encoderRNN(x, y)  # (Batch, SeqLength, P) -> (Batch, SeqLength, HiddenDim), ( Batch, HiddenDim)
        
        # features_reshaped = self.batch_norm(features_reshaped)
        print(traj_embedding.shape)
       output = self.hidden_layer1(traj_embedding)

        return output
model = DeepLMC(train_input_dim=train_x.shape[-1],
                seq_len=seq_lens, 
                embed_dim=10,
                encoder_hidden_size=64, 
                rnn_hidden_size=num_tasks,
                num_layers=2,
                state_dims= 11,
                action_dims=3,
                batch_size=batch_size,
                num_tasks=num_tasks, 
                num_hidden_dgp_dims=num_tasks,
                num_inducing1=num_inducing1,
                mean_type='constant')
model.to(device)

mll = DeepApproximateMLL(gpytorch.mlls.PredictiveLogLikelihood(model.likelihood, model, num_data=train_y.size(0), beta = 0.75))

history = []

variational_lrs =   1e-3 
hyperparam_lrs =  1e-3
variational_ngd_optimizer = gpytorch.optim.NGD(model.variational_parameters(), num_data=train_y.size(0), lr=variational_lrs)
hyperparameter_optimizer = torch_optimizer.AdaBound([
                    {'params': model.encoderRNN.encoder.parameters()},
                    {'params': model.encoderRNN.rnn.parameters(), 'weight_decay': 5e-4},
                    {'params': model.encoderRNN.traj_embed_layer.parameters()},
                    {'params': model.hidden_layer1.hyperparameters()},
                    {'params': model.likelihood.parameters()}, ], lr=hyperparam_lrs, betas=(0.75,0.999), weight_decay=0)
scheduler_optimizer = torch.optim.lr_scheduler.MultiStepLR(hyperparameter_optimizer, milestones=[30, 80, 140, 210, 290, 350], gamma=0.5)
abort = False

num_epochs = 401
min_loss = 1e10
history = []
model.train()
model.likelihood.train()
epochs_iter = tqdm.notebook.tqdm(range(num_epochs), desc="GP training Epoch")
losses=[]
for i in epochs_iter:
    loss_avg = 0.
    batch_counter = 0.
    minibatch_iter = tqdm.notebook.tqdm(train_loader, desc="Minibatch", total=len(train_loader),leave=False)  
    for x_batch, y_batch in train_loader:
        true_output=y_batch.view(y_batch.size(0)*y_batch.size(1),-1)
        variational_ngd_optimizer.zero_grad()
        print(f"input shape: {x_batch.shape}")
        pred = model(x_batch)    
        loss = -mll(pred, true_output )
        batch_counter += 1.
        loss.backward()        
        variational_ngd_optimizer.step()
        ### Perform Adam step to optimize hyperparameters
        hyperparameter_optimizer.zero_grad()
        pred = model(x_batch)
        loss = -mll(pred, true_output )
        history.append(loss.item())
        loss_avg += loss.item()
        if model._clip_gradient_norm > 0:
           torch.nn.utils.clip_grad_norm_(model.encoderRNN.parameters(), model._clip_gradient_norm)
        hyperparameter_optimizer.step()
 
        minibatch_iter.set_postfix(loss=loss.item())
    scheduler_optimizer.step()
    loss_avg = loss_avg / batch_counter
    losses.append(loss_avg)

```

This is my error message
```
     28 
     29     def __call__(self, *inputs, **kwargs):
---> 30         outputs = self.forward(*inputs, **kwargs)
     31         if isinstance(outputs, list):
     32             return [_validate_module_outputs(output) for output in outputs]

<ipython-input-23-23921a6140e3> in forward(self, input)
    529         # features_reshaped = self.batch_norm(features_reshaped)
    530         print(traj_embedding.shape)
--> 531         output = self.hidden_layer1(traj_embedding)
    532         
    533         return output

<ipython-input-23-23921a6140e3> in __call__(self, inputs, are_samples, **kwargs)
    354 
    355         # Now run samples through the GP
--> 356         output = ApproximateGP.__call__(self, inputs)
    357 
    358         ###############################################

/usr/local/lib/python3.7/dist-packages/gpytorch/models/approximate_gp.py in __call__(self, inputs, prior, **kwargs)
    106         if inputs.dim() == 1:
    107             inputs = inputs.unsqueeze(-1)
--> 108         return self.variational_strategy(inputs, prior=prior, **kwargs)

/usr/local/lib/python3.7/dist-packages/gpytorch/variational/lmc_variational_strategy.py in __call__(self, x, task_indices, prior, **kwargs)
    186             or ~gpytorch.distributions.MultivariateNormal (... x N)
    187         """
--> 188         latent_dist = self.base_variational_strategy(x, prior=prior, **kwargs)
    189         num_batch = len(latent_dist.batch_shape)
    190         latent_dim = num_batch + self.latent_dim

/usr/local/lib/python3.7/dist-packages/gpytorch/variational/variational_strategy.py in __call__(self, x, prior, **kwargs)
    240                 self.updated_strategy.fill_(True)
    241 
--> 242         return super().__call__(x, prior=prior, **kwargs)

/usr/local/lib/python3.7/dist-packages/gpytorch/variational/_variational_strategy.py in __call__(self, x, prior, **kwargs)
    305                 inducing_values=variational_dist_u.mean,
    306                 variational_inducing_covar=variational_dist_u.lazy_covariance_matrix,
--> 307                 **kwargs,
    308             )
    309         elif isinstance(variational_dist_u, Delta):

/usr/local/lib/python3.7/dist-packages/gpytorch/module.py in __call__(self, *inputs, **kwargs)
     28 
     29     def __call__(self, *inputs, **kwargs):
---> 30         outputs = self.forward(*inputs, **kwargs)
     31         if isinstance(outputs, list):
     32             return [_validate_module_outputs(output) for output in outputs]

/usr/local/lib/python3.7/dist-packages/gpytorch/variational/variational_strategy.py in forward(self, x, inducing_points, inducing_values, variational_inducing_covar, **kwargs)
    187         # Compute the mean of q(f)
    188         # k_XZ K_ZZ^{-1/2} (m - K_ZZ^{-1/2} \mu_Z) + \mu_X
--> 189         predictive_mean = (interp_term.transpose(-1, -2) @ inducing_values.unsqueeze(-1)).squeeze(-1) + test_mean
    190 
    191         # Compute the covariance of q(f)

RuntimeError: The size of tensor a (24655) must match the size of tensor b (0) at non-singleton dimension 2
```

I also used [this model](https://docs.gpytorch.ai/en/v1.6.0/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html) before  building a layer with multitask mean and covariances. However, the performance of the model was very disappointing. It seems the model wasn't able to infer different means and it didn't learn different structures of data. The input dimension of data is 14 and the output has 11 dimensions. 

I was searching to find a solution for this error. However, it is not clear where is the source of this input size and make it difficult to be able to debug it. I will appreciate if anyone can clarify whether it is a model problem or my implementation? Thanks.

**Comment by gpleiss** [comment] 2022-11-08 00:31
I've only had time to take a quick glance at this, but you should not use MultitaskMean and MultitaskKernel with variational models. They are only designed for ExactGPs. This is probably why you are getting the tensor sizing errors.

I'm also going to close this issue, since it is a problem with custom code (and not a bug in GPyTorch). Please open a discussion if you wish to discuss this further.

**Closed by gpleiss** 2022-11-08 00:31 UTC
Labels: bug
