### ISSUE TITLE
[Question] What is the difference between "model(test_x)" and "likelihood(model(test_x))" for prediction? 

### ISSUE THREAD

**Issue by mohammad-saber** [cornellius-gp/gpytorch#1409] opened 2020-12-31 06:47 UTC
Hi, 
I am trying regression with GPyTorch following the example in the [documentation](https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/Simple_GP_Regression.html). 

In the example, there are two ways to get mean and variance of prediction. 

1)

`f_preds = model(test_x)`

2)

`y_preds = likelihood(model(test_x))`

I noticed that the mean of prediction is the same when I use `model(test_x)` and `likelihood(model(test_x))`, but variance is different. I didn't understand the reason. 
More generally, I didn't understand the difference between `model(test_x)` and `likelihood(model(test_x))`. 

Could you please guide me on this issue?

**Comment by jacobrgardner** [comment] 2020-12-31 07:09
In the regression setting, the former does not include the likelihood noise (it is the latent variance) and the latter does include it.

**Comment by mohammad-saber** [comment] 2020-12-31 07:33
Thank you. 

Is likelihood noise similar to the noise that we can add to the kernel?  For example, when I define a kernel as below:

RBFKernel() + WhiteNoiseKernel()

I checked the list of kernels. I couldn't find "WhiteNoiseKernel()". It seems that GPyTorch adds noise automatically to the kernel. Is my understanding correct?

**Comment by gpleiss** [comment] 2020-12-31 20:23
Philosophically, it is different (is the "noise" due to your data observations or due to your uncertainty about your model). Practically, it is the same.

`WhiteNoiseKernel` has been replaced by [FixedNoiseGaussianLikelihood](https://docs.gpytorch.ai/en/stable/likelihoods.html#fixednoisegaussianlikelihood). This adds different observational noise for each data point. The standard GaussianLikelihood adds the same observational noise to each data point.

**Comment by ginward** [comment] 2021-01-21 23:48
> In the regression setting, the former does not include the likelihood noise (it is the latent variance) and the latter does include it.

Will the prediction performance be different between `model(test_x) `and `likelihood(model(test_x))`? 
For example, will `likelihood(model(test_x)) `be better?

**Comment by gpleiss** [comment] 2021-02-18 14:01
> Will the prediction performance be different between model(test_x) and likelihood(model(test_x))?
For example, will likelihood(model(test_x)) be better?

Let `X, y` be the training data, and let `x*, y*` be a test point.

`likelihood(model(test_x))` returns the posterior predictive distribution `p(y* | x*, X, y)`, whereas `model(test_x)` only returns the posterior distribution `p(f* | x*, X, y)`.

So yes - `likelihood(model(test_x))` should give better prediction performance, since `model(test_x)` is not a predictive distribution.

Closing for now - if there are more questions, please open up a [Discussion topic](https://github.com/cornellius-gp/gpytorch/discussions)

**Closed by gpleiss** 2021-02-18 14:01 UTC

**Comment by varunagrawal** [comment] 2022-12-12 05:20
Apologies for jumping onto this, but perhaps you should include these definitions in the documentation or point to the relevant resource. Took some of us noobs forever to figure this out.

**Comment by gpleiss** [comment] 2022-12-12 14:09
@varunagrawal absolutely. Any chance you'd be willing to put up a PR to update the documentation?

**Comment by varunagrawal** [comment] 2022-12-12 14:44
@gpleiss I was gonna do it even if you hadn't asked. I may need a couple of days though, lots of things need finishing up currently.

**Comment by varunagrawal** [comment] 2022-12-16 09:12
All done! @gpleiss can you or someone please review the PR? It should be linked right above this comment.
