### ISSUE TITLE
[Question] RunTimeError: Multitask GP with multiple GPU 

### ISSUE THREAD

**Issue by q8888620002** [cornellius-gp/gpytorch#1019] opened 2020-01-13 21:38 UTC
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```python

import math
import torch
import gpytorch
import pandas as pd 
import numpy as np
import gc

from matplotlib import pyplot as plt


cvsim_data = pd.read_csv("my_file")

cvsim_data.columns

unique_ids = cvsim_data.id.unique()
np.random.seed(1)
np.random.shuffle(unique_ids)

total_num_patients = len(unique_ids)
num_train = int(math.floor(0.8*total_num_patients))

train_ids = unique_ids[:num_train]
val_ids = unique_ids[num_train:]
### training 
train_x = cvsim_data.groupby("id", as_index=False).apply(lambda x: x.iloc[:-1])
train_x = train_x[train_x['id'].isin(train_ids)]

gp_data = train_x.drop(['id','Time'], axis = 1) 

## a n*d tensor
train_x = torch.tensor(gp_data.values).float()
 
train_y = cvsim_data.groupby("id", as_index=False).apply(lambda x: x.iloc[1:])
train_y = train_y[train_y['id'].isin(train_ids)]
gp_data = train_y.drop(['id','Time'], axis = 1)

## a n*32 tensor
train_y = torch.tensor(gp_data.values).float() 

### defining the multitask GP model

class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, n_devices):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)

        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ConstantMean(), num_tasks=32
        )

        base_covar_module = gpytorch.kernels.MultitaskKernel(
            gpytorch.kernels.RBFKernel(), num_tasks=32, rank=1
        )
        self.covar_module = gpytorch.kernels.MultiDeviceKernel(
            base_covar_module, device_ids=range(n_devices),
            output_device=output_device
        )
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)


# this is for running the notebook in our testing framework
def train(train_x,
          train_y,
          n_devices,
          output_device,
          checkpoint_size,
          preconditioner_size,
          n_training_iter,
):
    likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=32).to(output_device)
    model = MultitaskGPModel(train_x, train_y, likelihood, n_devices).to(output_device)
    
    model.train()
    likelihood.train()

    optimizer = torch.optim.Adam([
        {'params': model.parameters()},  # Includes GaussianLikelihood parameters
    ], lr=0.1)    # "Loss" for GPs - the marginal log likelihood
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    with gpytorch.beta_features.checkpoint_kernel(checkpoint_size), \
         gpytorch.settings.max_preconditioner_size(preconditioner_size):

        def closure():
	        optimizer.zero_grad()
	        output = model(train_x);print(train_x.size())
	        loss = -mll(output, train_y);print(output)
	        return loss
        loss = closure()
        loss.backward(retain_graph=True)

        for i in range(n_training_iter):

                options = {'closure': closure, 'current_loss': loss, 'max_ls': 10}
                loss, _, _, _, _, _, _, fail = optimizer.step(options);print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))

                if fail:
                    print('Convergence reached!');break

    print(f"Finished training on {train_x.size(0)} data points using {n_devices} GPUs.")
    return model, likelihood



output_device = torch.device('cuda:0')

train_x = train_x.to(output_device)
train_y = train_y.to(output_device)

n_devices = torch.cuda.device_count()
print('Planning to run on {} GPUs'.format(n_devices))


model, likelihood = train(train_x, train_y,\
                          n_devices=n_devices, output_device=output_device,\
                          checkpoint_size=500,\
                          preconditioner_size=1000,\
                          n_training_iter=20)

```

** Stack trace/error message **
```
RuntimeError: The size of tensor a (500) must match the size of tensor b (16000) at non-singleton dimension 0
```

## Expected Behavior
I would like to run a multitask GP, with n x d input on n x 32 output on multiple GPU, I followed and modified the [MultiTaskGP](https://gpytorch.readthedocs.io/en/latest/examples/03_Multitask_Exact_GPs/Multitask_GP_Regression.html) and [Exact GP Regression with Multiple GPUs and Kernel Partitioning
](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.html) examples but I kept getting the tensor mismatch error no matter what checkpoint_size.  

## System information

**Please complete the following information:**
-  GPyTorch v1.0.0
-   PyTorch 1.2
-   Linux 18.04

**Comment by gpleiss** [comment] 2020-01-13 22:52
This is likely a bug on our end. We have yet to test the multigpu code with multitask GPs.

As a quick fix for now: is your goal to use multiple GPUs for speed or scalability? I might recommend trying our our KeOps integration with a single GPU. It should be just as fast and scalable as the multi-GPU example. (See the [keops example notebook](https://gpytorch.readthedocs.io/en/latest/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.html) for a single-task example.)

**Comment by q8888620002** [comment] 2020-01-14 03:03
@gpleiss Thanks for the response. I have modified the code with KeOps example but now the error messages shows that 

````
RuntimeError: [KeOps] Arg number 3 : is not contiguous. Please provide 'contiguous' data array, as KeOps does not support strides. If you're getting this error in the 'backward' pass of a code using torch.sum() on the output of a KeOps routine, you should consider replacing 'a.sum()' with '(1. * a).sum()' or 'torch.dot(a.view(-1), torch.ones_like(a).view(-1))'. 
````
It seems to me that train_x, train_y are both contiguous. The modified code as as below

````

cvsim_data = pd.read_csv("my_file")

cvsim_data.columns

unique_ids = cvsim_data.id.unique()[:200]
np.random.seed(1)
np.random.shuffle(unique_ids)

total_num_patients = len(unique_ids)
num_train = int(math.floor(0.8*total_num_patients))

train_ids = unique_ids[:num_train]
val_ids = unique_ids[num_train:]

train_x = cvsim_data.groupby("id", as_index=False).apply(lambda x: x.iloc[:-1])
train_x = train_x[train_x['id'].isin(train_ids)]

gp_data = train_x.drop(['id','Time'], axis = 1) 
train_x = torch.tensor(gp_data.values).float()
train_x = train_x.contiguous() 


train_y = cvsim_data.groupby("id", as_index=False).apply(lambda x: x.iloc[1:])
train_y = train_y[train_y['id'].isin(train_ids)]
gp_data = train_y.drop(['id','Time'], axis = 1)

train_y = torch.tensor(gp_data.values).float() 
train_y = train_y.contiguous()

class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ConstantMean(), num_tasks=32
        )

###  modified gpytorch.kernels.RBFKernel(), num_tasks=32, rank=1 
###  into gpytorch.kernels.keops.RBFKernel(), num_tasks=32, rank=1 

        self.covar_module = gpytorch.kernels.MultitaskKernel(
            gpytorch.kernels.keops.RBFKernel(), num_tasks=32, rank=1
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)

    
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=32)
model = MultitaskGPModel(train_x, train_y, likelihood)

output_device = torch.device('cuda:0')

train_x = train_x.to(output_device)
train_y = train_y.to(output_device)
model = model.cuda()
likelihood = likelihood.cuda()


# this is for running the notebook in our testing framework
import os
smoke_test = ('CI' in os.environ)
training_iterations = 2 if smoke_test else 50

# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam([
    {'params': model.parameters()},  # Includes GaussianLikelihood parameters
], lr=0.1)

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iterations):
    optimizer.zero_grad()
    output = model(train_x)
    print(train_y.is_contiguous())
    loss = -mll(output, train_y)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
    optimizer.step()

````

**Comment by gpleiss** [comment] 2020-02-03 12:42
Sorry for the slow reply - everything is busy with ICML. This might be a bug in the KeOps code... I'll have to take a closer look. Is there any chance you can provide a full code example?

**Comment by gpleiss** [comment] 2023-06-02 22:07
Closing because checkpointing is now deprecated (as of v1.11)

**Closed by gpleiss** 2023-06-02 22:07 UTC
Labels: bug, multitask
