### ISSUE TITLE
[Docs]Something with the Cox Process example (Pyro low level interface)

### ISSUE THREAD

**Issue by ZhipengHuang00** [cornellius-gp/gpytorch#1340] opened 2020-11-09 21:11 UTC
# 📚 Documentation/Examples
Oh, hey, I've tried to run the example (the one with pyro integration: Cox process example), and I just copy and paste the code.  What I get the predicted intensity is not as good as the documentation shows. Is there anything wrong with this example? or anything I missed? The plot I got is as shown below.
![image](https://user-images.githubusercontent.com/50888674/98596481-7e5e7580-22a5-11eb-8308-205017bbea7a.png)

My PyTorch version is 1.6.0 and the pyro version is 1.3.1. It both should be fine.

- Link to [GPyTorch documentation](https://docs.gpytorch.ai/en/v1.1.1/examples/07_Pyro_Integration/Cox_Process_Example.html#Defining-the-quadrature-times)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/blob/master/examples/07_Pyro_Integration/Cox_Process_Example.ipynb)

**Comment by gpleiss** [comment] 2020-11-10 16:05
![Screen Shot 2020-11-10 at 11 03 59 AM](https://user-images.githubusercontent.com/824157/98698826-77d30b00-2344-11eb-9b3b-e873237bcfdf.png)

Try re-running the example. There's some randomness in the data and the optimization.

**Comment by ZhipengHuang00** [comment] 2020-11-10 21:01
Oh, Thanks for the reply. I found it does work when I tried it on Jupiter notebook but still get the bad results in Spyder.

Not sure what is going on (I have them exactly the same code in Jupiter notebook and Spyder), any ideas on this?

But anyway I could work on it in the Jupiter notebook.

**Comment by ZhipengHuang00** [comment] 2020-11-10 21:01
> ![Screen Shot 2020-11-10 at 11 03 59 AM](https://user-images.githubusercontent.com/824157/98698826-77d30b00-2344-11eb-9b3b-e873237bcfdf.png)
> 
> Try re-running the example. There's some randomness in the data and the optimization.

Oh, Thanks for the reply. I found it does work when I tried it on Jupiter notebook but still get the bad results in Spyder.

Not sure what is going on (I have them exactly the same code in Jupiter notebook and Spyder), any ideas on this?

But anyway I could work on it in the Jupiter notebook.

**Comment by gpleiss** [comment] 2020-11-11 19:25
I don't know what the issue is - I'm not familiar with Spyder. I'm closing this issue for now, but if you are able to find any other Spyder/Jupyter discrepancies let us know.

**Closed by gpleiss** 2020-11-11 19:25 UTC
Labels: documentation
