### ISSUE TITLE
[Question] Custom Likelihood function

### ISSUE THREAD

**Issue by jtm44** [cornellius-gp/gpytorch#2089] opened 2022-08-04 13:29 UTC
# 🐛 Bug

Hi.

 I am trying to implement a custom likelihood function for use in SVGP. The aim is to train the following model: y=g(f(x))+noise. Here f(x) is the output of the GP and is a latent variable. g(.) is a known function.

To begin, I have tried to implement a basic Gaussian likelihood function. The GPytorch inbuilt function appears to use the function distribution of f(x) directly rather than obtaining samples from it. To extend this to the model above, I need this to work by obtaining samples from f(x) so I can then pass them through g(.). However, the simple version shown below seems to have PSD issues. Can you spot any issues with my code? Thank you.

```python
class LikelihoodTest(Likelihood):
    def __init__(self):
        
        super(LikelihoodTest,self).__init__()
        self.noise_covar=HomoskedasticNoise()
     
    def _shaped_noise_covar(self, base_shape):
        return self.noise_covar(shape=base_shape)
    def forward(self, function_samples):
        noise = self._shaped_noise_covar(function_samples.shape).diag()
        return base_distributions.Normal(function_samples, noise.sqrt())
```

** Stack trace/error message **
```
NotPSDError: Matrix not positive definite after repeatedly adding jitter up to 1.0e-04.
```

**Comment by gpleiss** [comment] 2022-08-07 18:05
The `NotPSDError` is not coming from your likelihood, it's coming from somewhere else in your model. You will need to produce a full code example in order to get debugging help. Try to make the code example as minimal as possible while still reproducing the error.

Moreover, this is likely not a bug in GPyTorch, so I'm going to close this issue. Please open a [discussion](https://github.com/cornellius-gp/gpytorch/discussions) if you would like more debugging help or to continue the conversation. (If it turns out actually to be a bug in GPyTorch, we can open an issue based on the discussion.)

**Closed by gpleiss** 2022-08-07 18:05 UTC
Labels: bug

**Comment by jtm44** [comment] 2022-08-10 15:45
Thank you for your reply. I will open a discussion and include more detail.
Best wishes,
Joe
