### ISSUE TITLE
[Docs]

### ISSUE THREAD

**Issue by bharadwaj1098** [cornellius-gp/gpytorch#1735] opened 2021-08-22 03:47 UTC
# 📚 Documentation/Examples

`urllib.request.urlretrieve` failes to download 'elevators.mat' and 'bike.mat' for gpytorch/examples/05_Deep_Gaussian_Processes/Deep_Gaussian_Processes.ipynb and Deep_Sigma_Point_Process.ipynb. instead the formed files have HTML code with 
`<title>Google Drive - Virus scan warning</title>`

I feel it can be solved by changing the location of from Google drive to elsewhere.

**Comment by gpleiss** [comment] 2021-08-31 13:28
This is a duplicate of #1636 - but yes I think you have pinpointed the issue. cc/ @jacobrgardner

**Closed by gpleiss** 2021-08-31 13:28 UTC
Labels: documentation
