### ISSUE TITLE
[Question] Variance different from GPy with Batch Independent Multioutput GP

### ISSUE THREAD

**Issue by monabf** [cornellius-gp/gpytorch#1303] opened 2020-10-08 08:29 UTC
# Question: different predictive variance between GPy and GPyTorch in multi output case

Congrats for this great package!

I am porting my code for a project from GPy to GPyTorch, and wanted to make some simple comparisons first. I noticed that with the same kernel, in the single output case GPy and GPyTorch give me the same results, but in the multi output case, GPyTorch gives me much bigger variance than GPy. However, for both GPy and GPyTorch one independent GP should be used for each output dimension (default behavior in GPy + I am using Batch Independent Multioutput GP in GPyTorch). I gave both models the same kernel and hyperparameters. Does anyone know where the difference in the predictive variance comes from? Is there some structural difference that I overlooked?

Thanks for your help!

## To reproduce

```python
import GPy
import torch
import gpytorch
import logging
import math
import numpy as np
from matplotlib import pyplot as plt

class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, kernel):
        train_x = torch.squeeze(train_x)
        train_y = torch.squeeze(train_y)
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = kernel

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

    def optimize(self, likelihood, train_x, train_y, training_iter=50,
                 optimizer='Adam'):
        train_x = torch.squeeze(train_x)
        train_y = torch.squeeze(train_y)
        self.train()
        likelihood.train()
        if optimizer == 'Adam':
            optimizer = torch.optim.Adam(self.parameters(), lr=0.1)
        else:
            logging.error('Undefined optimizer')
        mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, self)
        for i in range(training_iter):
            # Zero gradients from previous iteration
            optimizer.zero_grad()
            # Output from model
            output = self(train_x)
            # Calculate loss and backpropagate gradients
            loss = -mll(output, train_y)
            loss.backward()
            optimizer.step()

    def predict(self, x, likelihood, full_cov=False):
        self.eval()
        likelihood.eval()
        with torch.no_grad(), gpytorch.settings.fast_pred_var():
            observed_pred = likelihood(self(x))
            if not full_cov:
                mean = observed_pred.mean
                var = observed_pred.variance
            else:
                mean = observed_pred.mean
                var = observed_pred.covariance_matrix
        return mean, var

class BatchIndependentMultitaskGPModel(ExactGPModel):
    def __init__(self, train_x, train_y, likelihood, kernel, output_size=1):
        super().__init__(train_x, train_y, likelihood, kernel)
        self.mean_module = gpytorch.means.ConstantMean(
            batch_shape=torch.Size([output_size]))
        self.covar_module = kernel

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        multitask_result = \
            gpytorch.distributions.MultitaskMultivariateNormal.from_batch_mvn(
                gpytorch.distributions.MultivariateNormal(mean_x, covar_x))
        return multitask_result

if __name__ == '__main__':
    # Multi input, single output
    train_x = torch.stack((
        torch.linspace(0, 1, 100), torch.linspace(0, 1, 100)), dim=1)
    train_y = torch.sin(train_x[:, 0] * (2 * math.pi)) + torch.randn(
        train_x[:, 0].size()) * math.sqrt(0.04)
    likelihood = gpytorch.likelihoods.GaussianLikelihood(
        noise_prior=gpytorch.priors.NormalPrior(0.04, 1))
    likelihood.noise = torch.tensor(0.04)  # init noise var
    lengthscale_prior = gpytorch.priors.MultivariateNormalPrior(
        torch.tensor([0.2, 0.2]),
        torch.diag(torch.tensor([6.0, 6.0])))
    outputscale_prior = gpytorch.priors.NormalPrior(1.0, 0.15)
    hypers = {'base_kernel.lengthscale': lengthscale_prior.mean,
              'outputscale': outputscale_prior.mean}
    kernel = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(
        ard_num_dims=train_x.shape[1]))
    kernel.initialize(**hypers)  # init kernel hyperparams
    model = ExactGPModel(train_x, train_y, likelihood, kernel)
    print(model.state_dict())
    # Evaluate GP by making predictions on test set
    test_x = torch.stack((
        torch.linspace(0, 1, 51), torch.linspace(0, 1, 51)), dim=1)
    with torch.no_grad(), gpytorch.settings.fast_pred_var():
        model.eval()
        likelihood.eval()
        observed_pred = likelihood(model(test_x))
        mean = observed_pred.mean.reshape(-1, 1)
        var = observed_pred.variance.reshape(-1, 1)
    lower = mean - 2 * torch.sqrt(var)
    upper = mean + 2 * torch.sqrt(var)
    # Compare GPy
    gpykernel = GPy.kern.RBF(input_dim=2, variance=1., lengthscale=0.2,
                             ARD=True)
    gpymodel = GPy.core.gp.GP(train_x.numpy(),
                              train_y.numpy().reshape(-1, 1),
                              kernel=gpykernel,
                              likelihood=GPy.likelihoods.Gaussian(
                                  variance=0.04),
                              inference_method=GPy.inference.latent_function_inference.ExactGaussianInference())
    print(gpymodel, gpymodel.kern.parameters)
    gpymean, gpyvar = gpymodel.predict(test_x.numpy())
    gpylower = (gpymean - 2 * np.sqrt(gpyvar)).reshape(-1,)
    gpyupper = (gpymean + 2 * np.sqrt(gpyvar)).reshape(-1,)
    gpymean = (gpymean).reshape(-1,)
    print('Same variance: ', gpyvar[0], var[0])
    # Initialize plot
    f, (ax1, ax2) = plt.subplots(2, 1)
    ax1.plot(train_x.numpy()[:, 0], train_y.numpy(), 'k*')
    ax1.plot(test_x.numpy()[:, 0], mean.numpy(), 'b')
    ax1.fill_between(test_x.numpy()[:, 0], lower.numpy()[:, 0],
                     upper.numpy()[:, 0],
                     facecolor='b', alpha=0.5)
    ax1.set_ylim([-3, 3])
    ax1.set_title('GPyTorch')
    ax1.legend(['Observed Data', 'Mean', 'Confidence'])
    ax2.plot(train_x.numpy()[:, 0], train_y.numpy(), 'k*')
    ax2.plot(test_x.numpy()[:, 0], gpymean, 'r')
    ax2.fill_between(test_x.numpy()[:, 0], gpylower, gpyupper, facecolor='r',
                     alpha=0.5)
    ax2.set_ylim([-3, 3])
    ax2.set_title('GPy')
    ax2.legend(['Observed Data', 'Mean', 'Confidence'])
    plt.show()

    # Multi input, independent multi output
    train_x = torch.stack((
        torch.linspace(0, 1, 100), torch.linspace(0, 1, 100)), dim=1)
    train_y = torch.stack((
        torch.sin(train_x[:, 0] * (2 * math.pi)) + torch.randn(
            train_x[:, 0].size()) * math.sqrt(0.04),
        3 * torch.square(
            torch.cos(train_x[:, 1] * (2 * math.pi))) + torch.randn(
            train_x[:, 1].size()) * math.sqrt(0.0001),
        3 * torch.square(
            torch.cos(train_x[:, 1] * (2 * math.pi))) + torch.randn(
            train_x[:, 1].size()) * math.sqrt(0.0001)), dim=1)
    train_y = torch.squeeze(train_y)
    likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(
        num_tasks=train_y.shape[1],
        noise_prior=gpytorch.priors.MultivariateNormalPrior(
            torch.tensor([0.04, 0.04, 0.04]),
            torch.diag(torch.tensor([1., 1, 1]))))
    likelihood.noise_covar.noise = torch.tensor([0.04])
    likelihood.noise = torch.tensor([0.04])
    lengthscale_prior = gpytorch.priors.MultivariateNormalPrior(
        torch.tensor([0.2, 0.2]),
        torch.diag(torch.tensor([6.0, 6.0])))
    outputscale_prior = gpytorch.priors.NormalPrior(1.0, 0.15)
    hypers = {'base_kernel.lengthscale': lengthscale_prior.mean,
              'outputscale': outputscale_prior.mean}
    kernel = gpytorch.kernels.ScaleKernel(
        gpytorch.kernels.RBFKernel(
            batch_shape=torch.Size([train_y.shape[1]]),
            ard_num_dims=train_x.shape[1]),
        batch_shape=torch.Size([train_y.shape[1]]))
    kernel.initialize(**hypers)  # init kernel hyperparams
    model = BatchIndependentMultitaskGPModel(train_x, train_y, likelihood,
                                             kernel,
                                             output_size=train_y.shape[1])
    print('multioutput')
    print(model.state_dict())
    # Evaluate GP by making predictions on test set
    test_x = torch.stack((
        torch.linspace(0, 1, 51), torch.linspace(0, 1, 51)), dim=1)
    mean, var = model.predict(test_x, likelihood)
    lower = mean - 2 * torch.sqrt(var)
    upper = mean + 2 * torch.sqrt(var)
    # Compare GPy
    gpykernel = GPy.kern.RBF(input_dim=2, variance=1.,
                             lengthscale=np.array([0.2, 0.2]), ARD=True)
    gpymodel = GPy.core.gp.GP(train_x.numpy(),
                              train_y.numpy(),
                              kernel=gpykernel,
                              likelihood=GPy.likelihoods.Gaussian(
                                  variance=0.04),
                              inference_method=GPy.inference.latent_function_inference.ExactGaussianInference())
    print(gpymodel, gpymodel.kern.parameters)
    print('Different variance: ', gpyvar[0], var[0])
    gpymean, gpyvar = gpymodel.predict(test_x.numpy())
    gpylower = gpymean - 2 * np.sqrt(gpyvar)
    gpyupper = gpymean + 2 * np.sqrt(gpyvar)
    gpymean = gpymean
    for j in range(train_y.shape[1]):
        f, (ax1, ax2) = plt.subplots(2, 1)
        ax1.plot(train_x.numpy()[:, 0], train_y.numpy()[:, j], 'k*')
        ax1.plot(test_x.numpy()[:, 0], mean.numpy()[:, j], 'b')
        ax1.fill_between(test_x.numpy()[:, 0], lower.numpy()[:, j],
                         upper.numpy()[:, j], facecolor='b', alpha=0.5)
        ax1.set_ylim([-3, 3])
        ax1.set_title('GPyTorch')
        ax1.legend(['Observed Data', 'Mean', 'Confidence'])
        ax2.plot(train_x.numpy()[:, 0], train_y.numpy()[:, j], 'k*')
        ax2.plot(test_x.numpy()[:, 0], gpymean[:, j], 'r')
        ax2.fill_between(test_x.numpy()[:, 0], gpylower[:, j],
                         gpyupper[:, j], facecolor='r', alpha=0.5)
        ax2.set_ylim([-3, 3])
        ax2.set_title('GPy')
        ax2.legend(['Observed Data', 'Mean', 'Confidence'])
        plt.show()
```

** Stack trace/error message **
```
OrderedDict([('likelihood.noise_covar.raw_noise', tensor([-3.2014])), ('likelihood.noise_covar.noise_prior.loc', tensor(0.0400)), ('likelihood.noise_covar.noise_prior.scale', tensor(1.)), ('mean_module.constant', tensor([0.])), ('covar_module.raw_outputscale', tensor(0.5413)), ('covar_module.base_kernel.raw_lengthscale', tensor([[-1.5078, -1.5078]]))])

Name : gp
Objective : -3.80029725079968
Number of Parameters : 4
Number of Optimization Parameters : 4
Updates : True
Parameters:
  gp.                      |  value  |  constraints  |  priors
  rbf.variance             |    1.0  |      +ve      |        
  rbf.lengthscale          |   (2,)  |      +ve      |        
  Gaussian_noise.variance  |   0.04  |      +ve      |         [gp.rbf.variance:
Param([1.]), gp.rbf.lengthscale:
Param([0.2, 0.2])]
Same variance:  [0.05287871] tensor([0.0529])
multioutput
OrderedDict([('likelihood.raw_noise', tensor([-3.2014])), ('likelihood.noise_covar.raw_noise', tensor([-3.2014, -3.2014, -3.2014])), ('likelihood.noise_covar.noise_prior.loc', tensor([0.0400, 0.0400, 0.0400])), ('likelihood.noise_covar.noise_prior._unbroadcasted_scale_tril', tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])), ('mean_module.constant', tensor([[0.],
        [0.],
        [0.]])), ('covar_module.raw_outputscale', tensor([0.5413, 0.5413, 0.5413])), ('covar_module.base_kernel.raw_lengthscale', tensor([[[-1.5078, -1.5078]],

        [[-1.5078, -1.5078]],

        [[-1.5078, -1.5078]]]))])

Name : gp
Objective : -65.64344697299347
Number of Parameters : 4
Number of Optimization Parameters : 4
Updates : True
Parameters:
  gp.                      |  value  |  constraints  |  priors
  rbf.variance             |    1.0  |      +ve      |        
  rbf.lengthscale          |   (2,)  |      +ve      |        
  Gaussian_noise.variance  |   0.04  |      +ve      |         [gp.rbf.variance:
Param([1.]), gp.rbf.lengthscale:
Param([0.2, 0.2])]
Different variance:  [0.05287871] tensor([0.1026, 0.1026, 0.1026])
```

## Expected Behavior

I would expect the same variance for GPy and GPyTorch in the independent output case.

## System information

- GPyTorch Version 1.2.0
- PyTorch Version 1.6.0
- Mac OS Catalina

**Comment by jacobrgardner** [comment] 2020-10-08 19:39
Hi @monabf,

At least with the current implementation of `MultitaskGaussianLikelihood`, things are working as intended. `MultitaskGaussianLikelihood` in the `rank=0` case currently learns the noise split as: (1) a noise for each task (specified by the entries of `likelihood.noise_covar.noise` and (2) a global constant noise that is shared across all tasks. Note that in the `rank>0` case this maybe makes a little bit more sense, as we'll instead learn a task covariance matrix plus a global diagonal shift.

The result of this is that when you do:
```python
likelihood.noise_covar.noise = torch.tensor([0.04])
likelihood.noise = torch.tensor([0.04])
```
you're basically doubling the amount of likelihood noise unintentionally. With the current implementation, this is fixed by making either of these small, e.g.:
```python
likelihood.noise_covar.noise = torch.tensor([0.04])
likelihood.noise = torch.tensor([1e-4])
```

Now, as to whether the current implementation is good, that is debatable. Certainly in the `rank=0` case things are pretty degenerate, since obviously adding a constant parameter to each of the task specific noises is not useful when doing optimization.

**Comment by monabf** [comment] 2020-10-09 08:11
Thanks a lot for your quick answer! Now I understand the results. Maybe it would make sense to explain the difference between `likelihood.noise_covar.noise` and `likelihood.noise` somewhere easy to find in the documentation, for example in the tutorial on hyperparameters, because I had been wondering what they meant for a while.

**Closed** 2020-10-09 16:35 UTC
Labels: discussion
