### ISSUE TITLE
Implementing Gibbs Kernel

### ISSUE THREAD

**Issue by atharvahans1** [cornellius-gp/gpytorch#1716] opened 2021-08-02 12:13 UTC
I was going through the available kernels in GpyTorch and couldn’t find the Gibbs covariance function given as:
![Screen Shot 2021-08-02 at 7 58 19 AM](https://user-images.githubusercontent.com/56398096/127859064-0fd0ad38-9f5c-4d11-aca5-6903c86885dd.png)
Would it be possible to have this kernel implemented in GPyTorch?

**Comment by gpleiss** [comment] 2021-08-02 17:24
Yes - we would accept a PR for this kernel function. See [these docs](https://docs.gpytorch.ai/en/stable/examples/00_Basic_Usage/Implementing_a_custom_Kernel.html) about implementing a custom kernel.

**Comment by atharvahans1** [comment] 2021-08-03 14:13
@gpleiss I have created the kernel function. Are there any tests to test my code?

**Comment by jacobrgardner** [comment] 2021-08-08 02:07
@atharvahans1 We have a series of base kernel test cases that you can extend here: https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/test/base_kernel_test_case.py

If after implementing the two abstract methods your kernel passes those tests, it's an indication that most model types in GPyTorch will work with your kernel.

**Comment by iwishiwasaneagle** [comment] 2021-11-25 14:30
> @atharvahans1 did you finish this ?

bump

**Comment by Jordy-VL** [comment] 2022-01-17 14:39
bump²

**Comment by charliebudd** [comment] 2023-05-18 10:01
This is a duplicate of https://github.com/cornellius-gp/gpytorch/issues/671

**Comment by gpleiss** [comment] 2023-05-24 21:16
Closed because it is a duplicate.

**Closed** 2023-05-24 21:16 UTC
Labels: enhancement
