### ISSUE TITLE
Sparse GP examples and deep GP examples

### ISSUE THREAD

**Issue by rtz19970824** [cornellius-gp/gpytorch#96] opened 2018-03-23 03:42 UTC
Hi,

Thanks for your amazing work. Will you consider add some sparse GP examples and deep GP examples? 

Regards

**Comment by jrg365** [comment] 2018-03-23 03:59
The KISS-GP examples are instances of a sparse GP algorithm. I don't think we have specific plans to implement other techniques, e.g. SGPR/SVGP in the immediate future. SGPR wouldn't necessarily be challenging to implement as a new `LazyVariable`, but our internal "to do" list is pretty long.

To be honest, I'm not totally sure what would be involved in implementing deep GPs. We do support deep kernel learning (e.g. the MNIST example notebook) for both classification and regression.

**Comment by rtz19970824** [comment] 2018-03-23 05:28
Thanks for your reply. ^_^ 
I think there may be some interests on a more general sparse GP. As you say, implementing SGPR/SVPG is not difficult with your library, but I think it's still a good way to help the beginners and show your library's flexibility.
DKL is an outstanding work. But I'm not sure if GP community will return to deep GPs in the future. I'm trying to implement deep GPs now. However I can only build a deep GP model by repeating a single GP (layer?). Maybe a GP module like torch.nn is better? I'm not sure.
Thanks for your reply again.

**Comment by jacobrgardner** [comment] 2018-05-07 18:44
SGPR is now implemented via the `InducingPointKernel` kernel and has an associated test at https://github.com/cornellius-gp/gpytorch/blob/master/test/examples/test_sgpr_regression.py. We eventually plan on making sure it is compatible with our variational inference, which will round out an implementation of SVGP.

It's worth emphasizing that we would expect SKI/KISS-GP (implemented via `GridInterpolationKernel`) 
to be faster than SGPR in essentially all cases where it is applicable (including DKL).

We are going to close the issue for now, since I don't believe we have any plans to implement deep GPs internally in the immediate future. Pull requests are of course welcome for such a thing!

**Closed by jacobrgardner** 2018-05-07 18:44 UTC
