### ISSUE TITLE
Ensure compatibility with breaking changes in pytorch master branch

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#74] opened 2018-02-26 14:50 UTC
This is a run of the simple_gp_regression example notebook on the current alpha_release branch. Running kissgp_gp_regression_cuda yields similar errors

```python
import math
import torch
import gpytorch
from matplotlib import pyplot as plt

%matplotlib inline
%load_ext autoreload
%autoreload 2
```

```python
from torch.autograd import Variable
# Training data is 11 points in [0,1] inclusive regularly spaced
train_x = Variable(torch.linspace(0, 1, 11))
# True function is sin(2*pi*x) with Gaussian noise N(0,0.04)
train_y = Variable(torch.sin(train_x.data * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2)
```

```python
from torch import optim
from gpytorch.kernels import RBFKernel
from gpytorch.means import ConstantMean
from gpytorch.likelihoods import GaussianLikelihood
from gpytorch.random_variables import GaussianRandomVariable
```

```python
# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        # Our mean function is constant in the interval [-1,1]
        self.mean_module = ConstantMean(constant_bounds=(-1, 1))
        # We use the RBF kernel as a universal approximator
        self.covar_module = RBFKernel(log_lengthscale_bounds=(-5, 5))
    
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        # Return moddl output as GaussianRandomVariable
        return GaussianRandomVariable(mean_x, covar_x)

# initialize likelihood and model
likelihood = GaussianLikelihood(log_noise_bounds=(-5, 5))
model = ExactGPModel(train_x.data, train_y.data, likelihood)
```

```python
# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use adam optimizer on model and likelihood parameters
optimizer = optim.Adam(list(model.parameters()) + list(likelihood.parameters()), lr=0.1)
optimizer.n_iter = 0

training_iter = 50
for i in range(training_iter):
    # Zero gradients from previous iteration
    optimizer.zero_grad()
    # Output from model
    output = model(train_x)
    # Calc loss and backprop gradients
    loss = -model.marginal_log_likelihood(likelihood, output, train_y)
    loss.backward()
    optimizer.n_iter += 1
    print('Iter %d/%d - Loss: %.3f   log_lengthscale: %.3f   log_noise: %.3f' % (
        i + 1, training_iter, loss.data[0],
        model.covar_module.log_lengthscale.data[0, 0],
        model.likelihood.log_noise.data[0]
    ))
    optimizer.step()
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-8-bdcf88774fd0> in <module>()
         14     output = model(train_x)
         15     # Calc loss and backprop gradients
    ---> 16     loss = -model.marginal_log_likelihood(likelihood, output, train_y)
         17     loss.backward()
         18     optimizer.n_iter += 1

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/models/exact_gp.py in marginal_log_likelihood(self, likelihood, output, target, n_data)
         43             raise RuntimeError('You must train on the training targets!')
         44 
    ---> 45         mean, covar = likelihood(output).representation()
         46         n_data = target.size(-1)
         47         return gpytorch.exact_gp_marginal_log_likelihood(covar, target - mean).div(n_data)

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/module.py in __call__(self, *inputs, **kwargs)
        158                 raise RuntimeError('Input must be a RandomVariable or Variable, was a %s' %
        159                                    input.__class__.__name__)
    --> 160         outputs = self.forward(*inputs, **kwargs)
        161         if isinstance(outputs, Variable) or isinstance(outputs, RandomVariable) or isinstance(outputs, LazyVariable):
        162             return outputs

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/likelihoods/gaussian_likelihood.py in forward(self, input)
         14         assert(isinstance(input, GaussianRandomVariable))
         15         mean, covar = input.representation()
    ---> 16         noise = gpytorch.add_diag(covar, self.log_noise.exp())
         17         return GaussianRandomVariable(mean, noise)

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/__init__.py in add_diag(input, diag)
         36         return input.add_diag(diag)
         37     else:
    ---> 38         return _add_diag(input, diag)
         39 
         40 

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/functions/__init__.py in add_diag(input, diag)
         18                        component added.
         19     """
    ---> 20     return AddDiag()(input, diag)
         21 
         22 

    /data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/experimental/ae/bento_kernel_ae_experimental#link-tree/gpytorch/functions/add_diag.py in forward(self, input, diag)
         12         if input.ndimension() == 3:
         13             diag_mat = diag_mat.unsqueeze(0).expand_as(input)
    ---> 14         return diag_mat.mul_(val).add_(input)
         15 
         16     def backward(self, grad_output):

    TypeError: mul_ received an invalid combination of arguments - got (Variable), but expected one of:
     * (float value)
          didn't match because some of the arguments have invalid types: (!Variable!)
     * (torch.FloatTensor other)
          didn't match because some of the arguments have invalid types: (!Variable!)

**Comment by gpleiss** [comment] 2018-02-26 15:20
I’m not getting the same error when I’m running the notebooks. What version of PyTorch are you using?

**Comment by Balandat** [comment] 2018-02-26 16:10
This is on the pytorch github master brach (commit 492466f25fdf12b62f2043587130e9ee393e4b1c, to be precise)

**Comment by gpleiss** [comment] 2018-02-26 16:27
Oh I see. We haven't tested the code on the latest version of PyTorch. I think right now everything is written for 0.3.1.

**Comment by Balandat** [comment] 2018-02-26 16:53
Let me see if I can track down the cause of this.

**Comment by Balandat** [comment] 2018-02-26 18:42
Turns out this is pretty hard to debug in my setup :(

**Comment by Balandat** [comment] 2018-02-26 19:10
fwiw, here are a couple of breaking changes over the last pytorch release:

#### TORCH.AUTOGRAD.FUNCTION OPERATES ON VARIABLES IN THE FORWARD() AND BACKWARD()

Previously, Function operated on Tensors in the forward() and sometimes in the backward(). Now,
`autograd.Function` operates on Variables in both the forward() and backward(). The returned values
must be Variables (and not Tensors).

#### SOME OPERATIONS NOW RETURN 0-D VARIABLES INSTEAD OF 1-D VARIABLES

Previously, indexing a 1-d Variable returned another 1-d Variable. It now returns a 0-d Variable (scalar).
Similarly, `var.sum()` used to return a 1-d Variable. It now returns a 0-d Variable.

**Comment by gpleiss** [comment] 2018-02-26 20:31
What we should do is start a pytorch0.4 branch that is compatible with this new change. I don’t know if we’d be able to have a version that is compatible with both 0.3 and 0.4 with that function breaking change.

We’re planning on merging alpha-release into master in a day or two. Once we do that we could start with a pytorch0.4 branch.

In the meantime, is it possible for you to work on pytorch 0.3?

**Comment by Balandat** [comment] 2018-02-26 23:41
That sounds like the right thing to do. How much work do you estimate it to make everything 0.4-compatible (assuming this function breaking change is the only thing)?

Unfortunately my setup is somewhat complicated, which makes working on anything but pytorch master surprisingly hard to do. TBH, it's probably easier to start working on making things compatible.

**Comment by jrg365** [comment] 2018-02-26 23:52
If those are the primary breaking changes, it might not be too much trouble. We'll need to actually install pytorch 0.4 to confirm, but for your error for example I would hazard a guess that the issue is just that we use `torch.eye` here:

https://github.com/cornellius-gp/gpytorch/blob/3e117ca2bde5e2ef5516a1cf930dc743c22aaf83/gpytorch/functions/add_diag.py#L11

which, since the inputs are now Variables in pytorch 0.4, just needs to be made a `Variable`. There's probably a few more errors of this variety (we create tensors in the forward/backward methods of Functions we create that now need to additionally be made `Variables`).

**Comment by Balandat** [comment] 2018-02-27 01:15
Yeah I tried that and it solved the issue with add_diag, but got caught somewhere else. I'll just have to put some time aside to work through this.

**Comment by gpleiss** [comment] 2018-02-28 14:48
`alpha_release` is now merged into master, fyi

**Comment by Balandat** [comment] 2018-02-28 14:53
Thanks. I have a few fixes that make the simple_gp_regression work with the current pytorch master, but it appears there is a lot more related to the Tensor/Variable and sum breaking changes that requires fixing.

I will start a new branch for what I have and send a pull request.

**Comment by jrg365** [comment] 2018-02-28 23:41
Is there a link where I can read about the breaking changes? I didn't actually see anything about it at https://github.com/pytorch/pytorch/releases. 

I am almost certainly worried about nothing here, but for the Variable change, I just want to sanity check that we fix it in a not-totally-ridiculous way. In particular, right now `linear_cg` (and `lanczos_tridiag` are intended **specifically** to operate on Tensors to avoid accumulating operations for autograd (i.e., backward propagating through the operations done in linear_cg could be pretty costly and a waste of time).

I assume the change is accompanied by some magic so that when Variables are used in forward passes, those operations "don't count" for autograd (since it'll use `backward()`), so as long as we only call linear_cg from within `forward()` and `backward()` of `Functions`, it'll do the right thing?

**Comment by Balandat** [comment] 2018-03-01 01:46
I guess the reason you didn't see anything in the release notes is that none of this has made its way in a public release yet. But I agree that things like this should be communicated more clearly, so folks like you don't operate under false assumptions. Let me see what I can dig up on this.

Anyway, these differences are minor details compared to the distinction between Tensors and Variables disappearing: https://github.com/pytorch/pytorch/issues/2633. The discussion there should hopefully provide some enough background to answer your questions.

**Comment by Balandat** [comment] 2018-03-01 01:58
Looks like once these additional changes go in, the previous ones may actually not be breaking anymore...

**Comment by jrg365** [comment] 2018-03-01 04:34
Okay, I gave the issue you linked a quick read, thanks for the pointer!

I am not 100% confident about this, but it sounds like we may be good on the efficiency front because PyTorch will no longer build computation graphs when using variables/tensors that have `requires_grad=False`.

I guess the simplest thing to do will just be to run some timing experiments once the code actually runs through.

**Comment by Balandat** [comment] 2018-03-02 23:44
Here's a post about the breaking changes: https://github.com/pytorch/pytorch/wiki/Breaking-Changes-from-Variable-and-Tensor-merge

**Comment by Balandat** [comment] 2018-03-07 04:02
Oh, this is fun. Now a call like `self._tensor_cls = type(self.representation()[0].data)` like [here](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/lazy/lazy_variable.py#L566) will not return the type of the tensor, but `Variable`, which of course breaks things. Note that
```
>>> t = torch.FloatTensor(3)
>>> t.type()
'torch.FloatTensor'
>>> type(t.data)
torch.autograd.variable.Variable
```

Looks like once the Variable/Tensor merge is somewhat more stable, what needs to happen is that all references to Variable in the pytorch_master branch need to be removed, so that exclusively Tensors are used throughout.

**Comment by darbour** [comment] 2018-03-07 04:13
As @gpleiss suggested, it seems like a fairly reasonable solution would be to have a branch that assumes the latest PyTorch push the github repo. Hopefully after the Tensor/Variable merge things will stabilize more...

**Comment by Balandat** [comment] 2018-03-08 21:32
This will be fixed in a backward-compatible way by https://github.com/cornellius-gp/gpytorch/pull/79.

By breaking compatibility with 0.3.0, we can use much cleaner api calls throughout - apart from getting rid of the Tensor/Variable distinction, we can instantiate a tensor of a particular data type by doing
`torch.zeros(dim1, ... dimk, dtype=some_other_tensor.dtype)`. Since this properly deals with all things cuda, and since similar support will be added to sparse tensors (https://github.com/pytorch/pytorch/issues/5641), this should make things much cleaner throughout. For instance, by adding a `dtype` property to `LazyVariable`, things could be simplified quite a bit.

**Comment by gpleiss** [comment] 2018-03-09 02:39
I would definitely be in favor of a `dtype` parameter for LazyVariables.

**Comment by Balandat** [comment] 2018-03-09 03:41
Cool, I have a local branch working, will push it to the pytorch_master branch soon.

**Comment by gpleiss** [comment] 2018-04-25 21:05
Finally have Travis set up for PyTorch 0.4 and 0.3.1. Looks like all the tests pass, so closing this issue.

Looking into the future, @jacobrgardner and I are planning on cutting an official alpha release (i.e. on pip, conda). As we're looking towards the beta, we'll start dropping support for PyTorch 0.3.

**Closed** 2018-04-25 21:06 UTC
Labels: compatibility

**Comment by Balandat** [comment] 2018-04-26 23:54
I guess 0.4 is now considered stable: https://github.com/pytorch/pytorch/releases/tag/v0.4.0
